services:
  - type: web
    name: spiralnet-memory-api
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NEO4J_URI
        sync: false      # set in Render dashboard (e.g., neo4j+s://<host>:<port>)
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: NEO4J_DATABASE
        value: neo4j
      - key: USE_NEO4J_VECTOR
        value: "false"   # set "true" only if vector plugin is available on your DB
